naver:
  client:
    id: ENC(wOhXtQ44Th7cKrMjJ5G+/VUI9hZiYlusM2NpLRoZamc=)
    secret: ENC(EUCjgEdMNYGkQ2g1F3VjX512plz7ffuB)
  openapi:
    url: https://openapi.naver.com/v1/search/news.json

jasypt:
  encryptor:
    password: "hwichan"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bird
    username: root
    password: 0917
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    properties:
        #        show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace