naver:
  client:
    id: ENC(wOhXtQ44Th7cKrMjJ5G+/VUI9hZiYlusM2NpLRoZamc=)
    secret: ENC(EUCjgEdMNYGkQ2g1F3VjX512plz7ffuB)
  openapi:
    url: https://openapi.naver.com/v1/search/news.json

price:
  client:
    id: dgi3CAcoiO5gPd49y1/LYA==
    secret: ENC(6LlAJB7vQpVRTo5DFZdoPkwGNB5/huG7sUk8FMGhce97xTzXRHxgF/6jJ+Hz1MDE)
  openapi:
    url: https://www.kamis.or.kr/service/price/xml.do

jasypt:
  encryptor:
    password: "hwichan"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bird
    username: root
    password: 0917
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace